### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/paperclip-document-rts8n1d9stne...

### ISSUE THREAD

**Issue by HLFH** [ekylibre/paperclip-document#4]
> Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/paperclip-document-rts8n1d9stne/6e0a9be89a097cecce18facf6597b4fa20230427-1129400-h2b7g4.pdf

Related to:

> app/exchangers/ekylibre/sales_exchanger.rb

```
   def link_document(sale)
        if @attachments_dir.present?
          attachment_potential_path = @attachments_dir.join(sale.client.name.parameterize,
                                                            sale.reference_number + ".*")
          attachment_paths = Dir.glob(attachment_potential_path)
          attachment_paths.each do |attachment_path|
            doc = Document.new(file: File.open(attachment_path))
            sale.attachments.create!(document: doc)
          end
        end
      end
```

> app/models/document.rb

```
 has_attached_file :file, path: ':tenant/:class/:id_partition/:style.:extension',
                           styles: {
                             default:   { format: :pdf, processors: %i[reader counter freezer], clean: true },
                             thumbnail: { format: :jpg, processors: %i[sketcher thumbnail], geometry: '320x320>' }
                           }
```

```
From: /root/ekylibre/app/exchangers/ekylibre/sales_exchanger.rb @ line 124 Ekylibre::SalesExchanger#link_document:

    115: def link_document(sale)
    116:   if @attachments_dir.present?
    117:     attachment_potential_path = @attachments_dir.join(sale.client.name.parameterize,
    118:                                                       sale.reference_number + ".*")
    119:     attachment_paths = Dir.glob(attachment_potential_path)
    120:     puts "THIS IS TOTALLY UNCOOL!!! #{attachment_paths}"
    121:     attachment_paths.each do |attachment_path|
    122:       puts "THIS IS UNCOOL!!! #{attachment_path}"
    123:       binding.pry
 => 124:       doc = Document.new(file: File.open(attachment_path))
    125:       sale.attachments.create!(document: doc)
    126:     end
    127:   end
    128: end
```

```
[1] pry(#<Ekylibre::SalesExchanger>)> attachment_paths
=> ["/root/ekylibre/db/first_runs/demo/alamano/sales/terrilacti/2019015026600.pdf"]
[2] pry(#<Ekylibre::SalesExchanger>)> Document.new(file: File.open(attachment_path)
[2] pry(#<Ekylibre::SalesExchanger>)* )  
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/paperclip-document-rtsgdq4v8shh/6e0a9be89a097cecce18facf6597b4fa20230427-1136690-1u499kj.pdf
from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/paperclip-document-0.0.11/lib/paperclip/document/processors/freezer.rb:23:in `initialize'
[3] pry(#<Ekylibre::SalesExchanger>)> Document.new(file: File.open(attachment_path[0])
[3] pry(#<Ekylibre::SalesExchanger>)* )  
Errno::EISDIR: Is a directory - read
from /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/fileutils.rb:1387:in `copy_stream'
Caused by Errno::EPERM: Operation not permitted @ rb_file_s_link - (/, /tmp/b14a7b8059d9c055954c92674ce6003220230427-1136690-10t7sn3)
from /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/fileutils.rb:297:in `link'
```

**Comment by HLFH** [comment]
Still the bug with `paperclip-document`, master branch.and `paperclip` latest version.
Version 6.1.0 of `paperclip` has a stability fix:

> STABILITY: Manually close Tempfiles when we are done with them (Erkki Eilonen).

Version does not matter here...

**Comment by HLFH** [comment]
```
[1] pry(main)> attachment_path = '/root/ekylibre/db/first_runs/demo/alamano/sales/terrilacti/2019015026600.pdf'
=> "/root/ekylibre/db/first_runs/demo/alamano/sales/terrilacti/2019015026600.pdf"
[2] pry(main)> File.open(attachment_path) 
=> #<File:/root/ekylibre/db/first_runs/demo/alamano/sales/terrilacti/2019015026600.pdf>
[3] pry(main)> Document.new(file: File.open(attachment_path))
[paperclip] Trying to link /root/ekylibre/db/first_runs/demo/alamano/sales/terrilacti/2019015026600.pdf to /tmp/6e0a9be89a097cecce18facf6597b4fa20230504-3993-5fym5y.pdf
[paperclip] Trying to link /tmp/6e0a9be89a097cecce18facf6597b4fa20230504-3993-5fym5y.pdf to /tmp/6e0a9be89a097cecce18facf6597b4fa20230504-3993-10r384r.pdf
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/paperclip-document-ru4xxscq0lsb/6e0a9be89a097cecce18facf6597b4fa20230504-3993-5fym5y.pdf
from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/paperclip-document-2439f9e5addb/lib/paperclip/document/processors/freezer.rb:23:in `initialize'
```

**Comment by HLFH** [comment]
Fixed.
